### ISSUE TITLE
Total unique users over the day

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_cloudmetrics#13]
This one is interesting as we want to be able to say 'here is some number for some time period' and possibly run it retrospecitvely, so lets say we run it at 00:10 am we want to run it from 0-24 the previous day. Maybe the rounding errors isn't worth worrying about, but it would be good to make sure we send explicit time stamps rather than assuming 'now' 

This will be one metric per day

**Comment by brendanheywood** [comment]
This could leverage https://github.com/catalyst/moodle-tool_cloudmetrics/issues/67

**Comment by jaypha** [comment]
This looks like an online users metric with a set daily frequency.

**Comment by brendanheywood** [comment]
Yeah sounds right. Feels slightly wrong just cloning or subclassing it to duplicate it, and we technically couldn't call it 'Daily unique users' because it strictly depends on the frequency being daily. But at least its easy.

Maybe have a think and see if there is a better way, like how hard would it be for a metric to have multiple instances and we could pass in the default frequency to the constructor and then you could still override it in config

**Comment by jaypha** [comment]
We could add a new table 'tool_cloudmetrics_metrics' (or something). metric\base can be refactored to derive from persistant, and the settings would be stored in the table rather than as configs. This would allow us to have multiple metrics of the same type. 

It would require some refactoring, but it shouldn't be difficult from the metric perspective. The most effort would be in redesigning the interface to make it work.

Perhaps this could be a 'stage 3' thing.

**Comment by brendanheywood** [comment]
Let’s just clone / subclass it for now then
