### ISSUE TITLE
Add metric for active users mtr_activeusers

### ISSUE THREAD

**Issue by jaypha** [catalyst/moodle-tool_cloudmetrics#2]
Add a metric to record active users and show on an internal report.

**Comment by brendanheywood** [comment]
This one should leverage the existing data from the registration data: (see pr about active users vs online users)

https://github.com/moodle/moodle/blob/master/lib/classes/hub/registration.php#L157

**Comment by brendanheywood** [comment]
@jaypha one thing I'd like you to think about soonish is the relationship between metric plugins and metrics, should they be 1-1 or should they be one to many? I'm leaning towards 1-N and this one might be a good example to illustrate it. For example we could call the plugin metric_registration and it exposes all of the numbers that the hub figures out eg:

Moodle release (4.0beta+)
Number of subjects (6)
Number of users (12517)
Number of recently active users (2)
Number of role assignments (10110)
Number of posts (5039)
Number of questions (0)
Number of resources (26)

This particular metric is fairly low on the priority list as its a very slow metric rather than a near real time one but others which are more real-time might be in the same boat but still be a family of related numbers. Maybe a better example could be something around live exams, and the number of students in a quiz, or waiting to start, or who have finished and they are all pumped out of the same complicated sql query or library call.

The other thing I'd like you to think about is the relationship between metrics and the metric plugin type. It would be good if these we not tightly coupled. ie it is very convenient to have a family of metrics defined by a plugin which is an mtr_xyz plugin, but it doesn't actually need to be an mtr plugin. This would enable us to have other plugins, say mod_quiz, define their own metrics internally. This isn't a must-have requirement, just something to think about and see how viable it is and steer that way. There is a lot of parallels with the Check API for inspiration.

**Comment by jaypha** [comment]
Implemented as part of #27
